### ISSUE TITLE
Car Position - Suggested Improvement / Potential Bug

### ISSUE THREAD

**Issue by Hysteria92** [eouia/MMM-VolvoOnCall#1]
Love the module and works fantastic. Took me a little while to get position info working and had to do some digging, but eventually found a potential bug in the code used to format the position value.

The regex used in node_helper.js within the reformValue function has a hole which means it falls over and returns a null position object, if the returned lat or long is negative.

I fixed this within my implementation by changing the following line:

var re = /([0-9\.]+)\,\s([0-9\.]+),\s\'([^\']+)\'/

to this:

var re = /([0-9\.\-]+)\,\s([0-9\.\-]+),\s\'([^\']+)\'/

Just escapes the '-' for negative lat and long values being returned.

Thought it was worth a mention and not sure if you had already found and resolved this issue, or whether you had given up development of this module.

Once again, awesome module and absolutely love your work. Hope the above helps.

**Comment by eouia** [comment]
Thanks for informing.
As you know, this module is hard to real test. 
If you can, making PR is always welcome.

**Comment by eouia** [comment]
updated.

**Comment by Hysteria92** [comment]
Awesome! Apologies, was busy working on my mirror last night and tweaking things - Didn't get chance to create the PR.

Thanks again for a fantastic little module :)

**Comment by eouia** [comment]
I can't maintain this module any more.
Have you interest to take new ownership of this module?
https://forum.magicmirror.builders/topic/12779/wanted-new-ownership-of-modules?page=1
